### PR TITLE
Static site pages #79

### PR DESCRIPTION
**Pull request by jakerockland**
This addresses issue #79 (not completed yet)

### CODE REVIEW

**Comment by jakerockland** [comment]
Having an issue with transferring the `call.html` page over to a `.md` file, as we can not use JS in the markdown file for the call loader. How do we want to go about handling this? Any thoughts @saikat?

**Comment by saikat** [comment]
Hey @jakerockland let me know when you believe this PR is ready to be merged.  For the call.html -- I sent an email but it seems like Github didn't add it as a comment.  Do you know if there is a way for us to use JS in our markdown?  It should technically be possible.  But the alternative would be to have call.html just get ported to be a React component (so we can make a call.jsx) that runs hte JS.   Then add a route to routes.jsx pointing /call to the right component.

**Comment by jakerockland** [comment]
@saikat I just have to move the /about page over, which I can do tonight when home from work, and then I think this should be ready to merge once we can work out the JS stuff. From the researching I did, it doesn't seem to be easy to include the JS in our markdown. I tried including it in a `<script></script>` tag pair and it ended up doing some really sketchy things with how the markdown was rendered, seems to be a strange bug that might be built into how the markdown is being converted to HTML? I'm not completely sure... 

Porting call.html to a React component may be more ideal. I can look into doing this, but don't have experience working with React really. What are the associated files in this repo that I should be looking at/are there any current examples of this being implemented on the site that I could look at as reference?

Also, I realized that this JS issue is also present on the `callteam.md` file, however we may want to tweak how that page looks a bit so that it is consistent with the rest of the other team pages, I'm trying to make all the team pages roughly consistent as I address #78 and #79 but will make another pass through at the end and do a final PR to make sure we address #5 before we call it settled 😛

**Comment by saikat** [comment]
Sweet, thank you so much for your work on this.  I'll follow up with how to
make a React component for the call page.  There may be a couple other team
pages that were relying on the calls JS to set up their own orientation
calls, so may be worth doing a final check on that as well.

**Comment by jakerockland** [comment]
Definitely! I'm looking forward to helping contributing to the Dev team however I can. That sounds great to me though, I'll definitely make sure I look that over though before we say this is ready for merge 👍

**Comment by jakerockland** [comment]
Finished moving over the last couple markdown files and took care of the other items from #79 as well. I think this should be ready to merge once we have the JS component worked out.

**Comment by jakerockland** [comment]
Will be ready once we have the JS bit worked out, probably won't have a chance to look more into it until this weekend as I'm not 100% on working with React yet.

**Comment by jakerockland** [comment]
But once the JS part is worked out, I think both this and #107 should be ready to merge.

**Pull request merged**
